<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Mapping as ORM;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFirstDateByCode($code)
    {
        $firstDate = $this->getEntityManager()->createQuery(
            'SELECT c.date FROM AppBundle:Currency c WHERE c.code=:code ORDER BY c.date ASC'
        )
            ->setParameter("code", $code)
            ->setMaxResults(1)
            ->getResult();

        return $firstDate[0]['date'];
    }

    public function getAverageCourseByCode($code)
    {

        $average = $this->getEntityManager()->createQuery(
            'SELECT AVG( c.midCourse ) FROM AppBundle:Currency c WHERE c.code=:code'
        )
            ->setParameter("code", $code)
            ->getResult();

        return $average;

    }

    public function getLastDate()
    {

        $last = $this->getEntityManager()->createQuery(
            'SELECT c.date FROM AppBundle:Currency c ORDER BY c.date'
        )
            ->setMaxResults(1)
            ->getResult();

        if (empty($last)) {
            $last = new \DateTime();
            $last->modify('-1 day');

            return $last;

        } else {
            return $last[0]['date'];
        }
    }

}
